server:
  port: 10001
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
spring:
  application:
    name: zuul

zuul:
  routes:
    provide: /provide/**
  ignored-services:
    - custom
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000

ribbon:
  ConnectTimeout: 500
  ReadTimeout: 3000